name: dialog_launcher
description: A Dart package to facilitate the creation and handling of dialog boxes in command line interfaces across different operating systems (Windows, Linux, and macOS).
version: 0.0.1
repository: https://github.com/Flutterando/dialog_launcher

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  process_run: ^0.13.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  dl: